Repository viclovsky/swagger-coverage, pull requests merged in 2020-11, with the labels that each got.

#62 NPE on tags builder
  build.gradle.kts
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/builder/postbuilder/TagStatisticsBuilder.java
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/Config.java
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/SimpleTest.java
  swagger-coverage-commandline/src/test/resources/configuration.json
  swagger-coverage-commandline/src/test/resources/petstory_no_tags.json
Labels: type:bug

#63 update tests, bump junit
  build.gradle.kts
  run.sh
  swagger-coverage-commandline/build.gradle.kts
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/configuration/ConfigurationBuilder.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/writer/FileSystemResultsWriter.java
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/SimpleTest.java
  swagger-coverage-commandline/src/test/resources/configuration.json
  swagger-coverage-commandline/src/test/resources/full_configuration.json
  swagger-coverage-rest-assured/build.gradle.kts
  swagger-coverage-rest-assured/src/test/java/com/github/viclovsky/swagger/coverage/RequestLoggerFilterTest.java
Labels: type:improvement

#61 Add deprecated status for endpoints
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/Results.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/builder/postbuilder/ConditionStatisticsBuilder.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/builder/prebuilder/CoverageStatisticsBuilder.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/data/ConditionCounter.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/data/CoverageCounter.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/data/CoverageOperationMap.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/data/OperationResult.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/writer/LogResultsWriter.java
  swagger-coverage-commandline/src/test/resources/swagger-coverage-output/two_coverage.json
  swagger-coverage-commons/src/main/resources/message.en
  swagger-coverage-commons/src/main/resources/message.ru
  swagger-coverage-commons/src/main/resources/report.ftl
  swagger-coverage-commons/src/main/resources/ui.ftl
Labels: type:new feature

#64 Fix error Can't convert boolean to string automatically
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/SimpleTest.java
  swagger-coverage-commandline/src/test/resources/petstory_with_x_example.json
  swagger-coverage-commons/src/main/resources/details/operation.ftl
Labels: type:bug

#68 fix npe in case of operation without tags
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/results/builder/postbuilder/TagStatisticsBuilder.java
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/SimpleTest.java
  swagger-coverage-commandline/src/test/resources/petstory_operation_wo_tags.json
Labels: type:bug
