Repository viclovsky/swagger-coverage, pull requests merged in 2022-02, with the labels that each got.

#102 add run.yml
  .github/workflows/run.yml
  run.sh
Labels: type:improvement

#101 Ability to configure the OpenAPI parser.
  README.md
  build.gradle.kts
  swagger-coverage-commandline/build.gradle.kts
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/configuration/Configuration.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/configuration/options/ConfigurationOptions.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/generator/Generator.java
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/CustomReportTemplateTest.java
  swagger-coverage-commandline/src/test/java/com/github/viclovsky/swagger/coverage/ParseOptionsTest.java
  swagger-coverage-commandline/src/test/resources/full_configuration.json
  swagger-coverage-commandline/src/test/resources/v3/operations/pet_petId.yaml
  swagger-coverage-commandline/src/test/resources/v3/petstory_ref_operations.yaml
  swagger-coverage-commons/src/main/resources/sections/summary.ftl
Labels: type:new feature

#100 replace log4j with logback
  build.gradle.kts
  swagger-coverage-commandline/build.gradle.kts
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/CommandLine.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/writer/FileSystemResultsWriter.java
  swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/writer/LogResultsWriter.java
  swagger-coverage-commandline/src/main/resources/log4j.properties
  swagger-coverage-commandline/src/main/resources/logback.xml
  swagger-coverage-commons/build.gradle.kts
Labels: type:bug
